name: CI/CD

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/GPSCPANEL_PROD
            git checkout main
            git pull origin main
            sudo chmod -R 777 storage bootstrap/cache
            export APP_DEBUG=false
            composer install --no-dev --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan portal:assert-assets
            sudo chmod -R 777 storage bootstrap/cache
